# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Bugbear/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Bugbear'
    organization: '210215-usf-net'
    scannerMode: 'MSBuild'
    projectKey: '210215-USF-NET_Bugbear-By-TeamPomodoro'
    projectName: 'Bugbear-By-TeamPomodoro'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Bugbear/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Bugbear/*.sln'

- task: SonarCloudAnalyze@1
  displayName: run code analysis

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
