# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Bugbear/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Bugbear'
    organization: '210215-usf-net'
    scannerMode: 'MSBuild'
    projectKey: '210215-USF-NET_Bugbear-By-TeamPomodoro'
    projectName: 'Bugbear-By-TeamPomodoro'
  
- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: 'Bugbear/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: 'Bugbear/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: 'test'
    projects: 'Bugbear/BBTest/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code Coverage"

- task: PublishCodeCoverageResults@1
  displayName: publish code coverage results
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coburtura/coverage.xml'

- task: SonarCloudAnalyze@1
  displayName: run code analysis

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (1f0ad125-9c6d-4dd3-a0e2-6bf5052dffe8)'
    appType: 'webAppLinux'
    WebAppName: 'bugbearapi'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'